apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
spec:
  replicas: 2
  selector:
    matchLabels: {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
