image:
  repository: docker.io/kkattl/frontend
  tag: latest

replicaCount: 2

service:
  type: ClusterIP
  port: 3000

envJs:
  API_BASE_URL: "https://habast.top/api/"
  REACT_APP_API_BASE_URL: "https://habast.top/api/"

ingress:
  enabled: true
  className: traefik              
  hosts:
    - host: habast.top
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - habast.top
      secretName: habast-top-tls
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.redirectscheme: "https"
