- name: Ensure /etc/rancher/k3s/k3s.yaml world‑readable
  become: yes
  file:
    path: /etc/rancher/k3s/k3s.yaml
    mode: "0644"

- name: Create .kube directory
  file:
    path: /home/ansible/.kube
    state: directory
    owner: ansible
    group: ansible
    mode: "0755"

- name: Copy kubeconfig to ansible home
  become: yes
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/ansible/.kube/config
    owner: ansible
    group: ansible
    mode: "0644"
    remote_src: yes 

- name: Export KUBECONFIG for future sessions
  become: yes
  lineinfile:
    path: /home/ansible/.bashrc
    line: 'export KUBECONFIG=$HOME/.kube/config'
    create: yes
    state: present
  when: ansible_env.SHELL is defined and ansible_env.SHELL != '/usr/sbin/nologin'