- name: Ensure python3‑kubernetes is present
  ansible.builtin.apt:
    name: python3-kubernetes
    state: present
    update_cache: yes     
  become: yes
  when: ansible_facts['os_family'] == 'Debian'


- name: Install kubernetes Python client via pip
  ansible.builtin.pip:
    name: "kubernetes>=25.3.0"
    executable: pip3
  become: yes
  when: ansible_facts['pkg_mgr'] != 'apt'  
