apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: myapp
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
    - host: habast.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-frontend
                port:
                  number: 3000
  tls:                         # 2 пробіли
    - hosts:                   # 4 пробіли
        - habast.top
      secretName: habast-top-tls