- name: Wait for k3s server
  ansible.builtin.wait_for:
    host: "{{ k3s_agent_server | regex_replace('^https?://', '') | regex_replace(':.*$', '') }}"
    port: 6443
    delay: 5
    timeout: 120

- name: Install k3s agent
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent" sh -
  args:
    creates: /usr/local/bin/k3s
  environment:
    K3S_URL: "{{ k3s_agent_server }}"
    K3S_TOKEN: "{{ k3s_agent_token }}"
  async: 300
  poll: 0
  register: agent_job

- name: Wait for k3s agent install to finish
  ansible.builtin.async_status:
    jid: "{{ agent_job.ansible_job_id }}"
  register: agent_job_result
  until: agent_job_result.finished
  retries: 30
  delay: 10
  failed_when: agent_job_result.rc != 0

- name: Ensure k3s config directory exists
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Write k3s agent config
  ansible.builtin.copy:
    dest: /etc/rancher/k3s/config.yaml
    content: |
      server: "{{ k3s_agent_server }}"
      token: "{{ k3s_agent_token }}"
    owner: root
    group: root
    mode: '0600'
  notify: restart k3s-agent


- name: Ensure k3s-agent service is running
  ansible.builtin.service:
    name: k3s-agent
    state: started
    enabled: yes
