- name: Wait for k3s server
  ansible.builtin.wait_for:
    host: "{{ k3s_agent_server | regex_replace('^https?://', '') | regex_replace(':.*$', '') }}"
    port: 6443
    delay: 5
    timeout: 120

- name: Install k3s agent
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | K3S_URL={{ k3s_agent_server }} K3S_TOKEN={{ k3s_agent_token }} sh -
  args:
    creates: /usr/local/bin/k3s
  async: 300
  poll: 0
  register: agent_job

- name: Wait for k3s agent install to finish
  ansible.builtin.async_status:
    jid: "{{ agent_job.ansible_job_id }}"
  register: agent_job_result
  until: agent_job_result.finished
  retries: 30
  delay: 10

- name: Ensure k3s-agent service is running
  ansible.builtin.service:
    name: k3s-agent
    state: started
    enabled: yes
