apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels: {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "backend.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "backend.labels" . | nindent 8 }}
    spec:
      containers:
      - name: tomcat
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        {{- range $k,$v := .Values.env }}
        - name: {{ $k }}
          value: "{{ $v }}"
        {{- end }}
        envFrom:
        - secretRef:
            name: backend-secret