- name: Install Docker
  ansible.builtin.apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
