postgresql:
  auth:
    username: myuser
    password: mypass            
    database: mydb
  primary:
    persistence:
      enabled: true
      size: 10Gi               
  resources:                    
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  metrics:
    enabled: true               